name: Build-Windows-Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  actions: read

jobs:
  build-linux:
    runs-on: windows-latest
    steps:
      # --- SSH for private submodule ---------------------------------
      - name: Set up SSH for private submodules
        run: |
          npm run install:all
          npm run build
      # --- upload build artifact------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmnaiView-windows-${{ github.ref_name }}
          path: build/OmnAIView
