name: Build-Windows-Binary

permissions:
  actions: read

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH for private submodules
        run: |
          npm run install:all
          npm run build
      # --- upload build artifact------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmnaiView-windows-${{ github.ref_name }}
          path: |
            electron\out\make\squirrel.windows\x64\RELEASES
            electron\out\make\squirrel.windows\x64\*.nupkg"
            electron\out\make\squirrel.windows\x64\*.exe
