name: Build-Windows-Binary

permissions:
  actions: read

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: windows-latest
    steps:
      - name: Debug - show working directory and contents
        run: |
          echo "PWD: $PWD"
          dir
      - name: Checkout repository
        uses: actions/checkout@v4
      # --- SSH for private submodule ---------------------------------
      - name: Set up SSH for private submodules
        working-directory: .
        run: |
          npm run install:all
          npm run build
      # --- upload build artifact------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmnaiView-windows-${{ github.ref_name }}
          path: build/OmnAIView
